### ISSUE TITLE
Fatal error: concurrent map writes

### ISSUE THREAD

**Issue by jm33-m0** [jm33-m0/emp3r0r#34]
```
goroutine 2447 [chan send, 12 minutes]:
github.com/jm33-m0/emp3r0r/core/lib/cc.reverseBash.func2.1(0xc0001aeae0)
        lib/cc/rshell.go:53 +0x6d
github.com/jm33-m0/emp3r0r/core/lib/cc.reverseBash.func2(0xc0001aeae0, 0xc0002583a0, 0x981ac0, 0xc000107940)
        lib/cc/rshell.go:59 +0x228
created by github.com/jm33-m0/emp3r0r/core/lib/cc.reverseBash
        lib/cc/rshell.go:50 +0x165

goroutine 2446 [chan receive, 12 minutes]:
github.com/jm33-m0/emp3r0r/core/lib/cc.reverseBash.func1(0xc00006a6c0, 0xc0002583a0, 0x981ac0, 0xc000107940)
        lib/cc/rshell.go:34 +0x4d
created by github.com/jm33-m0/emp3r0r/core/lib/cc.reverseBash
        lib/cc/rshell.go:33 +0x114

goroutine 2465 [chan receive, 12 minutes]:
github.com/jm33-m0/emp3r0r/core/lib/cc.reverseBash.func4(0xc000201500, 0xc00000e0e8, 0xc0001aeae0, 0xc000266d70, 0x981ac0, 0xc000107940)
        lib/cc/rshell.go:135 +0x52
created by github.com/jm33-m0/emp3r0r/core/lib/cc.reverseBash
        lib/cc/rshell.go:134 +0x494
```

**Comment by jm33-m0** [comment]
Hard to investigate, unable to reproduce, closing for now
