### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by h0nus** [jm33-m0/emp3r0r#40]
Just downloaded and used `python3 build.py cc`

```
Clean everything and start over? [Y/n] Y
CC server address (domain name or ip address, can be more than one, separate with space):
> XXXXXX.XXX
[!] Generating new certs...
>> generating a certificate authority
Generating RSA private key, 2048 bit long modulus (2 primes)
..+++++
...................................+++++
e is 65537 (0x010001)
req: Skipping unknown attribute "prompt"
<< certificate authority generated.
>> creating serial
>> generating a keypair for: 06ebf456-c6d7-11eb-b926-979f681e338f
.. key
Generating RSA private key, 2048 bit long modulus (2 primes)
............................+++++
........................................................+++++
e is 65537 (0x010001)
.. request
.. certificate
Signature ok
subject=CN = 06ebf456-c6d7-11eb-b926-979f681e338f.com
Getting CA Private Key
.. removing key password
writing RSA key
<< 06ebf456-c6d7-11eb-b926-979f681e338f keypair generated.
[!] Exception:
Traceback (most recent call last):
  File "build.py", line 656, in <module>
    main(sys.argv[1])
  File "build.py", line 429, in main
    gobuild.build()
  File "build.py", line 87, in build
    self.set_tags()
  File "build.py", line 293, in set_tags
    "DoHServer = \"\"", f"DoHServer = \"{CACHED_CONF['doh_server']}\"")
KeyError: 'doh_server'
```

am i missing something?

**Comment by jm33-m0** [comment]
You are missing `doh_server` in `build.json`, but it's supposed to have to default value in `build.py`

I will fix this
