### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xxlimit** [jm33-m0/emp3r0r#46]
Im am currently running Ubuntu 20.04.3 LTS aswell go goversion of 1.16.1
I was trying to run the build.py

```
go: github.com/mholt/archiver@v3.1.1+incompatible: missing go.sum entry; to add it:
	go mod download github.com/mholt/archiver
run cryptor.exe
sh: 1: ./cryptor.exe: not found
[!] Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'agent.packed.exe' -> '../core/./build/cc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./build.py", line 629, in <module>
    main(sys.argv[1])
  File "./build.py", line 400, in main
    gobuild.build()
  File "./build.py", line 162, in build
    shutil.move("agent.packed.exe", f"../core/{targetFile}")
  File "/usr/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'agent.packed.exe'

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "./build.py", line 503, in save
    readline.append_history_file(new_h_len - prev_h_len, hfile)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by jm33-m0** [comment]
#43

**Comment by jm33-m0** [comment]
Try fixing `../packer`'s dependencies

**Comment by xxlimit** [comment]
For any noobies looking at this you go to packer and run `go mod tidy`
