### ISSUE TITLE
AttributeError: 'GoBuild' object has no attribute 'AgentRoot'  

### ISSUE THREAD

**Issue by Anibabasb** [jm33-m0/emp3r0r#53]
./build.py cc
Clean everything and start over? [Y/n] y
CC server address (domain name or ip address, can be more than one, separate with space):
> 127.0.0.1
[!] Exception:
Traceback (most recent call last):                                           
  File "/home/kali/Downloads/emp3r0r-1.1.2/core/./build.py", line 709, in <module>                                                                        
    main(sys.argv[1])                                                        
  File "/home/kali/Downloads/emp3r0r-1.1.2/core/./build.py", line 479, in main                                                                            
    gobuild = GoBuild(target="cc", cc_ip=ccip, cc_other_names=cc_other)      
  File "/home/kali/Downloads/emp3r0r-1.1.2/core/./build.py", line 110, in __init__                                                                        
    CACHED_CONF['agent_root'] = self.AgentRoot                               
AttributeError: 'GoBuild' object has no attribute 'AgentRoot'

**Comment by jm33-m0** [comment]
Thanks for reporting, this is a bug of `build.py` introduced by the latest commit, you can use older versions until it's been fixed

**Comment by jm33-m0** [comment]
Also, please note that when using `build.py`, you need to specify the `--target cc` argument now, try `./build.py --help`

https://github.com/jm33-m0/emp3r0r/wiki/Getting-started#build-cc

**Comment by jm33-m0** [comment]
Hi, it's been fixed in master branch and a new version has been released, please check

**Comment by jm33-m0** [comment]
https://github.com/jm33-m0/emp3r0r/commit/a00a147b379af4f10a925ea310afa023edf563ef

Turns out it was another bug, anyways, both have been fixed
